### ISSUE TITLE
P.56 symfony newコマンド

### ISSUE THREAD

**Issue by kenjis** [hidenorigoto/symfony2-book#1]
```
$ symfony new classic-symfony2.7
```

となっていますが、スペースが抜けてしまってます。

```
$ symfony new classic-symfony 2.7
```

「Windowsの場合」も同様です。

**Comment by hidenorigoto** [comment]
ご連絡ありがとうございます！
正誤情報記載とともに、本ページで分かりやすく案内するように対応させていただきます。

**Comment by hidenorigoto** [comment]
closed via https://github.com/hidenorigoto/symfony2-book/commit/465df4b2f52d6850abf74e16ee577fd0a156c84f
