### ISSUE TITLE
P.119 図4-14 お問い合わせ種別

### ISSUE THREAD

**Issue by kenjis** [hidenorigoto/symfony2-book#10]
スクリーンショットで

> ●お問い合わせ種別： 0

となっていますが、P.117のリスト4-21では

``` twig
●お問い合わせ種別： {% if data.type == 0 %}公演について
{% else %}その他
{% endif %}
```

となっているため整合していません。

**Comment by hidenorigoto** [comment]
@kenjis 
ありがとうございます。スクリーンショットを差し替えるよう対応させていただきます。

![20151228 mail-profile](https://cloud.githubusercontent.com/assets/89830/12013282/b06a4348-ad56-11e5-9a02-9c0a3c0e292a.png)

**Comment by hidenorigoto** [comment]
closed via 10373fe70535e667336ffc9c614c0ec2284fba2b
