### ISSUE TITLE
[p159~160]バリデーショングループ設定後,一般ユーザーのお問い合わせ画面でエラー

### ISSUE THREAD

**Issue by hanahiroAze** [hidenorigoto/symfony2-book#12]
p160ではバリデーショングループadminを設定後に、一般ユーザーのお問い合わせ画面から送信すると、「問題なく動作するはずです」とありますが、

p157~158にてカラム(process_status,process_memo)追加時に当該カラムがnull許可の設定になっていないため、未入力の場合insertに失敗します。
なお、当該カラムをnull許可にした場合は、正常に動作しました。

参考)エラーメッセージ

```
An exception occurred while executing 'INSERT INTO inquiry (process_status, process_memo, name, email, tel, type, content) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, "\u3063\u3063d", "xxx@gmail.com", null, 0, "ssss"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'process_status' cannot be null
```

環境情報 
Symfony 2.7.8

**Comment by hidenorigoto** [comment]
@hanahiroAze 
ありがとうございます！

p.157のリスト6-8にて、Inquiryエンティティに `$processStatus` と `$processMemo` の2つのフィールドを追加していますが、この時あわせてコンストラクタにてこれらのフィールドの初期値をセットするコードも追加しています。 @hanahiroAze さんの手元では、こちらのコードも追加されているかご確認いただけないでしょうか。

**Comment by hanahiroAze** [comment]
@hidenorigoto 実装が漏れておりました。失礼いたしました。
