### ISSUE TITLE
p.30コマンドが実行できない

### ISSUE THREAD

**Issue by sunohara** [hidenorigoto/symfony2-book#13]
ページ:30
コンソールコマンド`php app/console`を実行すると、`Could not open input file: app/console`と表示され実行されません。参考書296ページの開発環境は、行っておりません。その影響でしょうか？

**Comment by hidenorigoto** [comment]
ありがとうございます。

お使いの環境や、書籍の中でどの時点まで実行が完了されているのか、確認させてください。

p.30の `php app/console` の実行は、次のような状態で行う想定です。
- p.26からの「Symfonyの準備」にてSymfony Installerをインストールしてある
- p.28からの「Symfony Installerでのデモアプリケーションの準備」にて、デモアプリケーションをダウンロードしている
- デモアプリケーションダウンロード後、デモアプリケーションのディレクトリへ移動している（p.28にある「cd symfony_demo」というコマンドの部分）
- p.28下の「インストール後の動作確認」が完了している

この状態で実行するものです。
これらは正常に実行できているかどうか、教えて下さい。
（書籍と異なる手順で実行されている点などあれば、それも教えてください）

`Could not open input file: app/console` というメッセージが表示されるのは、以下のような原因が考えられます。
- コマンドを実行するディレクトリが間違っているかもしれません。
- もしくは、そもそも「app」というディレクトリがあるのかどうかをご確認ください。（どのようなディレクトリがあるのか教えて下さい）

**Comment by sunohara** [comment]
ご多忙の中、ご丁寧にありがとうございます。
いただいたコメントの内容に添って確認いたします。
