### ISSUE TITLE
P.168 お問い合わせ検索機能の作成でエラー

### ISSUE THREAD

**Issue by YasMatu** [hidenorigoto/symfony2-book#16]
初めまして”P.168 お問い合わせ検索機能”のエラーが発生し行き詰まってしまったのでご教授願います。

リスト6-16～18までを実装し、管理画面から”お問い合わせ管理"をクリックすると

Undefined method 'findAllByKeyword'. The method name must start with either findBy or findOneBy!
500 Internal Server Error - BadMethodCallException

というエラーが表示されてしまいます。

P167の問い合わせ編集画面までは上手く動作していたので、環境は問題ないかと思っています。

よろしくお願いします。

●環境
Windows10
Xampp V3.2.2
Symfony V2.8.9

**Comment by hidenorigoto** [comment]
@YasMatu 

エラーメッセージの内容は、Doctrineのエンティティリポジトリ（この箇所では InquiryRepository クラス）に `findAllByKeyword()` というメソッドがない、というものです。ですので、InquiryRepository クラスにこのメソッドがまだ実装されていない状態なのではないかと思われます。

リスト6-17の記載の仕方がやや分かりづらいかもしれませんが、先頭の use 文の追加以外に、（リスト6-17では5行目以降にあたる） `public function findAllByKeyword($keyword)` から始まるメソッドの実装も行ってください。

もし上記のメソッドも正しく実装済みということであれば、原因の特定が難しいのですが、一度キャッシュクリアをお試しください。

**Comment by YasMatu** [comment]
連休中にもかかわらず回答頂きありがとうございます！
サポートサイトに掲載されてるダウンロードファイルにあるch07start.zipを解凍し、classic-symfony\src\AppBundle\EntityフォルダにInquiryRepository.phpをコピーしたのでタイプミスは無いと思います。
同様にAdminInquiryListController.phpもclassic-symfony\src\AppBundle\Controllerフォルダにコピーしました。

php app/console cache:clearも行ってみて、Chrome、firefox等別のブラウザでも試してみたのでですが、原因が特定出来ずにいます。
エラーイメージを貼っておきます。
https://drive.google.com/file/d/0B3YAt7M-l4j6TXY2REVaOXFCamc/view?usp=sharing


```
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByKeyword($keyword)
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.name LIKE :keyword')
            ->orWhere('i.tel LIKE :keyword')
            ->orWhere('i.email LIKE :keyword')
            ->orderBy('i.id', 'DESC')
            ->setParameters([
                ':keyword' =>'%'.$keyword.'%'
            ])
            ->getQuery();

        return new ArrayCollection($query->getResult());
    }
}

```

**Comment by hidenorigoto** [comment]
@YasMatu 

なるほど、頂いた画像のログから分かる範囲では、コントローラ（AdminInquiryListController）からリポジトリ（InquiryRepository）のメソッドを呼び出す際に、正しく InquiryRepository が使われておらず、Doctrineがデフォルトで用意するスタブの方が呼び出されてしまっているのかもしれません。

エンティティクラス `Inquiry` の、クラスのアノテーションはどのようになっているか教えて頂けるでしょうか？
（Inquiryクラスの上に記述した `@ORM\Table` や `@ORM\Entity` の部分です。p.129あたりで記述がでてきます）

**Comment by YasMatu** [comment]
回答ありがとうございます。原因が判りました！
Inquiry.phpの部分が

 `* @ORM\Entity(repositoryClass="AppBundle\Repository\InquiryRepository")
`

のままにしていました。

` * @ORM\Entity(repositoryClass="AppBundle\Entity\InquiryRepository")
`

にした所正常に動作しました。

貴重なお時間を使わせてしまって申し訳ありませんでした！

**Comment by hidenorigoto** [comment]
@YasMatu 
無事解決されたようで、よかったです！
