### ISSUE TITLE
p.167 管理者用画面のお問い合わせ編集画面でボタン「保存」を押すとエラー

### ISSUE THREAD

**Issue by kazz-oga** [hidenorigoto/symfony2-book#17]
p.167の図6-6「管理者用画面のお問い合わせ編集画面」でボタン「保存」を押すと次のエラーがでます。
　Expected argument of type "null or string", "integer" given

解決策が解らず、学習が止まっています。助けてください。

Symfony 3.3.13
PHP 7.2.12
MacOS 10.14

**Comment by kazz-oga** [comment]
違う現象も出ていることがわかりました。

・「ステータス」欄、「対応メモ」欄が双方ともに選択なし、値を設定しないときはsubmitされない
・「ステータス」欄の選択をせず、「対応メモ」欄に値を設定するとsubmitされない。
・「ステータス」欄の選択をおこない、「対応メモ」欄に値を設定しないとsubmitされて、
　　Expected argument of type "null or string", "integer" given
　となる

何らかのコーティングミスがあるかもしれない。

**Comment by kazz-oga** [comment]
var_dumpで内部の動きを確認しました。
p167の画面中のchoice「状態」の３番目の処理とだけ、Form.phpのLine606の$this->config->getCompound()がtrueになります。1番目、2番目のときはfalseです。
falseの場合は選択された値が渡ってエラーにはならないようです。trueの場合は、
不定な値が後ろに流れて上記メッセージが出ているように見受けられます。

なお、p149のフォームでも確認しました。choice「type」の二つの項目についてはともにForm.phpのLine606の$this->config->getCompound()の値はfalseです。

解決のヒントでもいただけないでしょうか

**Comment by kazz-oga** [comment]
Form.phpにvar_dumpを入れて確認しています。

Form.php(Line609)の$this->config->getEmptyData()が
正常に進むときはNULL、上記の異常のときはint(0)で返ってきているようです。
(メッセージに一致。Expected argument of type "null or string", "integer" given)

Form.phpは親のフォーム、子(choiceの各項目)のフォームの処理のために再帰呼び出しをしています。
子のフォームの処理が終わって、再帰呼び出しから戻って、親のフォームのprocessStatusの処理で
618行目の$this->config->getEmptyData()がint(0)となっているようです。

なお、p108の「お問い合わせ」で、親に戻ってtypeに対してはNULLを返して正常に処理しています。

ヒントでも結構です。対応策があれば教えてください。

**Comment by kazz-oga** [comment]
とりあえず、Form.php(line614)に次のパッチを当てて、学習を先に進めることにしました。

if(is_integer($emptyData)){var_dump("Form.php:614 ",$emptyData);$emptyData=NULL;}

**Comment by kazz-oga** [comment]
symfonyを3.4.22にバージョンアップし、解決しました。

**Comment by xahagiwara** [comment]
p163のリスト6-11でchoiceの
'empty_data' => 0を
'empty_data' => '0'に変更したら動きました

Symfony 2.7.50
PHP 7.2.13
MacOS 10.14.1
