### ISSUE TITLE
P.46 http://127.0.0.1:8000/blog/

### ISSUE THREAD

**Issue by kenjis** [hidenorigoto/symfony2-book#3]
> ブラウザからhttp://127.0.0.1:8000/blog/にアクセスし、

とありますが、`No route found for "GET /blog/"`になりました。

http://127.0.0.1:8000/ja/blog/であれば、本書の記述の通りになりました。

**Comment by hidenorigoto** [comment]
@kenjis 
ありがとうございます。demoアプリケーションが多言語対応した分の対応漏れでした。
ページ内にいくつか `/blog/` があるため、同様に訂正させていただきます。

**Comment by hidenorigoto** [comment]
closed via bd63fbf5d804b78e87912248343f61e5b6d2f545
