### ISSUE TITLE
P.50 TimedTwigEngine

### ISSUE THREAD

**Issue by kenjis** [hidenorigoto/symfony2-book#4]
6行目

> TimedTwigEngineというクラスが…

と記述されていますが、リスト2-7にそのようなクラスはありません。

**Comment by hidenorigoto** [comment]
@kenjis 
こちらはバージョンアップデート時にリストを更新した際に追随が漏れておりました。
TwigEngineに訂正いたします。

**Comment by hidenorigoto** [comment]
closed via 161229aac507c13929db119463cbc31ffca1b879
