### ISSUE TITLE
P.157 脚注

### ISSUE THREAD

**Issue by kenjis** [hidenorigoto/symfony2-book#7]
> コマンド処理前のクラスファイルは、先頭に~が付いたファイル名で…

とありますが、手許の環境では末尾に~が付きました。

```
$ php app/console doctrine:generate:entities AppBundle:Inquiry
Generating entity "AppBundle\Entity\Inquiry"
  > backing up Inquiry.php to Inquiry.php~
  > generating AppBundle\Entity\Inquiry
```

**Comment by hidenorigoto** [comment]
@kenjis 
ありがとうございます。末尾の間違いですね。訂正いたします。

Doctrine ORMのコードを見ると、過去には先頭につけていた名残があるようですが、2011年のコミットで末尾に変更されていますね。
https://github.com/doctrine/doctrine2/commit/9a8e8ce35d6fbf38d638e9cd34e80b5894c3b69b

**Comment by hidenorigoto** [comment]
closed via d8c99401bf5c80366ef84ef631c1f8d85abd73d2
