### ISSUE TITLE
P.155 リスト6-5 findAll()

### ISSUE THREAD

**Issue by kenjis** [hidenorigoto/symfony2-book#9]
`indexAction()`の中のコードが以下のようになっています。

``` php
$inquiryList = $inquiryRepository->findAll([], ['id' => 'DESC']);
```

しかし、本来の意図としては、以下のように`findBy()`ではないかと思います。

``` php
$inquiryList = $inquiryRepository->findBy([], ['id' => 'DESC']);
```

文中の解説には、

> すべてのエンティティを降順で取得…

とありますので。

ただし、P.156の図6-4は、降順にはなっていません。それを正しいとすれば、

``` php
$inquiryList = $inquiryRepository->findAll();
```

でしょうか。

**Comment by hidenorigoto** [comment]
@kenjis 
ありがとうございます。

`findAll()` を `findBy()` へ訂正させていただきます。

**Comment by hidenorigoto** [comment]
図6-4の差し替え
![20151228 inquiry-list](https://cloud.githubusercontent.com/assets/89830/12013917/5c7be3d2-ad64-11e5-81b7-6c09c6a9a637.png)

**Comment by hidenorigoto** [comment]
closed via 1f0a662ae8e36a5c8c05db464979b9f827a75b7a, 3323e0f381faf87d4d7f86cb29b9f9ccc233d071, 9ceef80972f56cc8482662c92e68b270cbf11498
